name: Build Obsidian api-documenter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api-documenter/**'
      - 'api-extractor/**'

permissions:
  contents: write # For GH Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code, API Documenter fork
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Build Rushstack
        continue-on-error: true
        run: |
          rush update --bypass-policy
          rush build

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_number }}
          body: |
            Obsidian rushstack fork binary. This is used to generate the TypeScript API inside the [Obsidian Developers Documentation](https://docs.obsidian.md).
          draft: false
          prerelease: false
          files: |
              ./apps/api-documenter/bin/api-documenter
              ./apps/api-extractor/bin/api-extractor
