name: Build Obsidian api-documenter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api-documenter/**' # Only run this workflow whenever a file in ./api-documenter has changed.

permissions:
  contents: write # For GH Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code, API Documenter fork
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Build Rushstack
        continue-on-error: true
        run: |
          rush update --bypass-policy
          rush build
      - name: Get package version - API Documenter
        working-directory: ./apps/api-documenter
        id: get_version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Commit and Create Git tag
        id: create_tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "chore(release): :bookmark: v${{steps.get_version.outputs.version }}-${{ github.run_number }}
          update Obsidian API Documenter fork"
          git tag -a v${{ steps.get_version.outputs.version }}-${{ github.run_number }} -m "Release v${{ steps.get_version.outputs.version }}-${{ github.run_number }}"
          git push origin v${{ steps.get_version.outputs.version }}-${{ github.run_number }}
          git push origin main
          echo "tag=v${{ steps.get_version.outputs.version }}-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release v${{ steps.get_version.outputs.version }}-${{ github.run_number }}
          tag_name: ${{ steps.create_tag.outputs.tag }}
          body: |
            Release v${{ steps.get_version.outputs.version }}-${{ github.run_number }}
            Obsidian API Documenter fork binary. This is used to generate the TypeScript API inside the [Obsidian Developers Documentation](https://docs.obsidian.md).
          draft: false
          prerelease: false
          files: ./apps/api-documenter/bin/api-documenter
